module.exports = {
  camelcase: require('./camelCase'),
  curly: require('./curly'),
  debug: require('./debugger'),
  decimals: require('./decimals'),
  emptyStatement: require('./emptyStatement'),
  eqeqeq: require('./eqeqeq'),
  initUndefined: require('./initUndefined'),
  invalidConstructor: require('./invalidConstructor'),
  invokeConstructors: require('./invokeConstructors'),
  isNan: require('./isNan'),
  multivar: require('./multiVar'),
  nonew: require('./newSideEffects'),
  parseIntRadix: require('./parseIntRadix'),
  plusplus: require('./updateExpression'),
  rmdelete: require('./rmdelete'),
  snakecase: require('./snake_case'),
  sub: require('./dotNotation'),
  trailingCommas: require('./trailingCommas'),
  useLiteral: require('./useLiteral')
}
